name: release
on:
  push:
    branches:
      - 'master'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: suzuito/create-release-by-file@v1.0.0
#       - run: python version.py LATEST_VERSION
#       - run: git config --global user.email "auto@example.com"
#       - run: git config --global user.name "auto"
#       - run: git tag -a `cat LATEST_VERSION` -F LATEST_VERSION.md
#       - run: git push origin `cat LATEST_VERSION`