name: test
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  test:
    name: Run unit test ${{ matrix.go }}
    strategy:
      matrix:
        go: [ '1.12.x', '1.13.x' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: ./test
      - uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: /tmp/artifacts
      - run: python version.py
      - run: git tag -a `cat LATEST_VERSION` -F LATEST_VERSION.md
      - run: git push origin `cat LATEST_VERSION`